site_name: 'Sikker'
site_url: http://norse.blue
site_author: 'NorseBlue'
site_favicon: favicon.ico
copyright: 'Copyright Â© 2016 NorseBlue'
repo_url: https://github.com/norse-blue/php-sikker
repo_name: 'GitHub'
theme: readthedocs
pages:
  - Getting Started:
    - Introduction: 'index.md'
    - Installation: 'getting-started/installation.md'
    - Usage: 'getting-started/usage.md'
  - About:
    - License: 'about/license.md'
